version: "3"
services:
  app:
    restart: unless-stopped
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - ./env/development.env
    extra_hosts:
      - "host.docker.internal:host-gateway"

  nginx:
    container_name: nginx_intern
    restart: unless-stopped
    image: "nginx:latest"
    ports:
      - "80:80"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - app
    extra_hosts:
      - "host.docker.internal:host-gateway"
