version: "3"
services:
  app:
    restart: always
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - ./env/development.env

  nginx:
    container_name: nginx_intern
    restart: always
    image: "nginx:latest"
    ports:
      - "80:80"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - app
  networks:
  db_network:
    driver: bridge
  web_network:
    driver: bridge
